### PR TITLE
Annotation: Added documentation about writing concrete values to memory

### PR DESCRIPTION
**Pull request by sebastianwalla**
Signed-off-by: Sebastian Walla
<sebastian.walla@gmx.de>

### CODE REVIEW

**Comment by vitalych** [comment]
Something is wrong with your commit, it includes way too many things. Perhaps you forgot to rebase.

**Comment by sebastianwalla** [comment]
I think I fixed it now

**Comment by adrianherrera** [comment]
I don't think so. It says that `src/Howtos/s2e.so.rst` is conflicting. I don't think you have the latest version checked out

**Comment by sebastianwalla** [comment]
I hope its now resolved

**Comment by adrianherrera** [comment]
Thanks!

**Pull request merged**
