### PR TITLE
Windows DLL tutorial

### PR DESCRIPTION
**Pull request by adrianherrera**
This goes with https://github.com/S2E/s2e-env/pull/28

### CODE REVIEW

**Comment by adrianherrera** [comment]
Updated this PR with some general cleanups of the docs

**Comment by vitalych** [comment]
LGTM! Someone who tries it on a fresh setup will approve.

**Comment by adrianherrera** [comment]
What's wrong with this. Why can't I merge :\

**Comment by adrianherrera** [comment]
Closing because there seems to be some bug that is stopping me from merging this. Github claims that it is waiting for the CLA status to be reported, but it also says that all contributers have signed the CLA.

I will reopen a new PR.

**Pull request closed without merging**
