### PR TITLE
Google CTF 2016 tutorial

### PR DESCRIPTION
**Pull request by adrianherrera**
A tutorial on how to solve a CTF challenge with S2E :)

It is dependent on https://github.com/S2E/s2e-env/pull/43 because it uses the new rebuild functionality.

### CODE REVIEW

**Comment by vitalych** [comment]
Nice tutorial! Did you try to use the Lua annotation plugin in order to kill states on success? It would be much simpler than writing a new plugin. I've also encountered the constraint problem when trying to solve the defcon ctf. I thought we could have some sort of generic plugin that describes the input grammar. These are thoughts for the future, perhaps you could write a section about it in this tutorial to give ideas to others.

**Comment by adrianherrera** [comment]
Err no, I've actually never used that plugin. I'll have a look at it tomorrow.

**Comment by adrianherrera** [comment]
Right, so I found the documentation in the old S2E -> https://github.com/dslab-epfl/s2e/blob/master/docs/Plugins/Annotation.rst

So what do you think? I think maybe we could leave the tutorial "as is", because I think it does a "good" job of explaining S2E internals a bit more. Then I could add a new section at the end that explains how to do it "the easy way" with the Lua annotation plugin.

What do you think?

**Comment by vitalych** [comment]
Adding a section to show how to use Lua annotations would make sense. It's simpler that writing C++ plugins, as it doesn't require re-compiling from scratch. I would present Lua method first.

**Comment by adrianherrera** [comment]
Ok. In that case the old Lua annotation documentation (that was purposefully removed) should be reintroduced and brought up to date (when I had a quick look at it this week the function names seemed to be different to what was in the source).

Unless there is something fundamentally wrong with this PR, can we just merge it now? I will do the Lua documentation in another PR.

**Pull request closed without merging**
